algo = input('Digite algo: ')
print('o tipo primitivo dele é: ', type(algo))
print('ele é composto somente de espaços?:',algo.isspace())
print('ele é alphabetico?:',algo.isalpha())
print('ele é numérico?: ',algo.isnumeric())
print('ele está em maiúsculo?: ',algo.isupper())
print('ele está em minúsculo?: ', algo.islower())
print('ele é alphabetico e númerico?:' ,algo.isalnum())
print('Está capitalizada?: ', algo.istitle())
