n1 = int(input('Digite o número para ver sua tabuada: '))

print('1: {}'.format(n1*1))
print('2: {}'.format(n1*2))
print('3: {}'.format(n1*3))
print('4: {}'.format(n1*4))
print('5: {}'.format(n1*5))
print('6: {}'.format(n1*6))
print('7: {}'.format(n1*7))
print('8: {}'.format(n1*8))
print('9: {}'.format(n1*9))
print('10: {}'. format(n1*10))
